sudo: required
language: generic 
services:
    - docker

before_install:
    - docker build -t cruzee/docker-sample-app -f Dockerfile.dev .

script:
    - docker run -e CI=true cruzee/docker-sample-app npm run test